apiVersion: v2
name: mlflow
description: A Helm chart for MLFlow
type: application
version: 1.5.2
appVersion: 1.18.0
keywords:
  - mlflow
home: https://mlflow.org/
icon: https://mlflow.org/docs/latest/_static/MLflow-logo-final-black.png
source:
  - https://github.com/cetic/helm-mlflow
maintainers:
  - name: Andrew Miller
    email: andrew.miller@qucelerate.co
    url: https://github.com/QuCelerate
dependencies:
  - name: postgresql
    version: ~10.3.6
    repository: https://charts.bitnami.com/bitnami
    condition: db.default.enabled
